# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [latest] # 其他分支可通过给 master 分支创建一个 WIP 的 PR 查看结果是否正确
    tags: ["v*"]
  pull_request:
    branches: [latest]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# For softprops/action-gh-release
permissions:
  contents: write
  discussions: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          apt-get update -y
          apt-get install --no-install-recommends -y \
            cmake ninja-build zlib1g-dev libzstd-dev \
            clang-20 llvm-20-dev mlir-20-tools libmlir-20-dev
          find . -type f -exec touch {} + # https://github.com/ninja-build/ninja/issues/1599
          MLIR_DIR=/usr/lib/llvm-20/lib/cmake/mlir CC=clang-20 CXX=clang++-20 utils/build.sh
          cmake --build Testing -t test
          cat Testing/Testing/Temporary/LastTest.log
